# Generated by Django 4.1.5 on 2023-01-25 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fullname", models.CharField(max_length=200)),
                ("mothername", models.CharField(max_length=200, null=True)),
                ("email", models.EmailField(max_length=254, null=True, unique=True)),
                (
                    "Gender",
                    models.CharField(choices=[("male", "female")], max_length=50),
                ),
                ("birthday", models.DateField()),
                ("blood_group", models.CharField(max_length=200)),
                ("nationality", models.CharField(max_length=200)),
                ("personalID", models.CharField(max_length=200)),
                ("profile_pic", models.ImageField(blank=True, null=True, upload_to="")),
                ("images", models.ImageField(upload_to="")),
                ("description", models.TextField(blank=True, null=True)),
                ("docfile", models.FileField(upload_to="documents/%Y/%m/%d")),
                ("license_id", models.CharField(max_length=200)),
                ("vehicle_id", models.CharField(max_length=200)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
