# Generated by Django 4.1.5 on 2023-01-25 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_customer_profile_pic_alter_customer_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='license_id',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='personalID',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='vehicle_id',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
