# Generated by Django 4.1.5 on 2023-01-25 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_customer_gender_alter_customer_license_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='images',
            field=models.ImageField(upload_to=''),
        ),
    ]
